// agui-guard — deny-first execution gate for the /agui chat surface. The agentic chat loop can
// call side-effecting tools (run_command/start_command spawn a HOST shell; delete_file/move_file
// are irreversible), and the endpoint is localhost-bound but UNAUTHENTICATED — any local process
// or a plain `curl` POST could otherwise drive arbitrary command execution against the host. This
// gate requires a per-launch execution TOKEN (generated by the main process, held there, and
// delivered only to the trusted renderer over IPC) before any gated tool runs.
//
// FAIL-SAFE BY DESIGN: with no/invalid token the gated tools are DENIED — but the turn still
// chats, reasons, reads, searches, and writes notes into the vault. A wiring hiccup degrades to
// "no host-exec", never a broken app. Reads/prose/vault-writes are ungated (low harm); only
// host-exec + irreversible ops must be earned. This is DUIN's "earned autonomy" applied to the
// one surface that was allow-everything. Pure + unit-tested.

/** Host-exec + irreversible file ops — earned, never default. write_file/edit_file are not in
 *  this STATIC set: for an IN-VAULT target their blast radius is the vault, so gating them would
 *  break ordinary note-taking for no security gain. But a write_file that ESCAPES the vault into
 *  an operator-permitted root (e.g. the Desktop) IS earned — it is gated DYNAMICALLY at the seam
 *  (agui-gate computes pathEscapesVault; decideAguiGate then classes it tier 'irreversible-file'),
 *  taking the same exec-token + posture path as delete/move. edit_file needs an existing file and
 *  does a snapshotted surgical replace — a strictly smaller surface than a fresh write — so it
 *  stays ungated even out-of-vault for now. */
export const AGUI_GATED_TOOLS = new Set([
  'run_command',
  'start_command',
  'delete_file',
  'move_file',
  // send_email is an IRREVERSIBLE external side effect (an email, once sent, cannot
  // be recalled). Gating it here means a de-privileged turn (execOk:false — an
  // inbound channel turn carries no exec token) is denied at the deny-first
  // exec-token rule BEFORE any posture/policy can permit it, so an untrusted inbound
  // message can never make DUIN send mail on its own. A trusted/authorized turn
  // still routes through per-action approval (see decideAguiGate + output-tool-pack).
  'send_email',
  // spawn_agent is gated too: a subagent runs the SAME host-exec / irreversible tools in a nested
  // loop, so an ungated spawn_agent is an unauthenticated side-door to everything above. Gating it
  // here blocks the spawn itself for unauthorized turns; the subagent ALSO re-checks the token on
  // its own dangerous tools (defense-in-depth) so the bypass is closed at two layers.
  'spawn_agent',
  // create_skill writes a SKILL.md that is LIVE-LOADED as an executable capability (and NOT
  // vault-path-jailed — it targets the skills dir), so an inbound/untrusted turn creating one is a
  // path to persistent new behavior the operator never authored. Gated so a de-privileged turn
  // (execOk:false — an inbound channel turn carries no exec token) is denied at the deny-first
  // rule before any posture can permit it; a trusted turn still routes through per-action approval
  // (brain-tool-registry requiresApproval:true).
  'create_skill',
  // delegate_task spawns an EXTERNAL harness as a child process (services/executor/). That is
  // shell access by construction, so it takes the same deny-first exec-token path as spawn_agent
  // and lands on the spawn-recursive tier; its descriptor (requiresApproval + sandboxBypass risk)
  // floors it on every unattended surface. See PLANNING/DUIN_EXTERNAL_EXECUTOR_PLAN.md.
  'delegate_task'
])

export function isGatedTool(name: unknown): boolean {
  return typeof name === 'string' && AGUI_GATED_TOOLS.has(name)
}

/**
 * Constant-time token comparison. An empty/absent server token OR header → unauthorized
 * (fail-safe deny). Length-mismatch short-circuits (lengths aren't secret); equal-length inputs
 * are compared without early-exit so a caller can't time the first differing byte.
 */
export function execAuthorized(headerToken: unknown, serverToken: string | null | undefined): boolean {
  if (!serverToken || typeof headerToken !== 'string' || headerToken.length === 0) return false
  if (headerToken.length !== serverToken.length) return false
  let diff = 0
  for (let i = 0; i < serverToken.length; i++) diff |= headerToken.charCodeAt(i) ^ serverToken.charCodeAt(i)
  return diff === 0
}

/** The model-facing tool result when a gated tool is denied — explains the gate honestly so the
 *  model routes around it (answers in prose / uses ungated tools) instead of retrying blindly. */
export function deniedResult(toolName: string): string {
  return (
    `Error: '${toolName}' was blocked by DUIN's deny-first execution gate — this turn is not ` +
    `authorized to run system commands or perform irreversible file operations. Host-exec and ` +
    `destructive ops require the app's execution token; reads, searches, and vault note writes are ` +
    `unaffected. Continue by answering directly or using a read/search/write_file tool instead.`
  )
}
